version: "3"

services:
  janusgraph:
    image: janusgraph/janusgraph:0.5.2
    container_name: grapl-janusgraph
    environment:
      gremlinserver.threadPoolWorker: 2
    ports:
      - "8182:8182"