version: "3"

services:
  janusgraph:
    image: janusgraph/janusgraph:0.5.2
    container_name: grapl-janusgraph
    volumes:
      - "../conf/jg-server-conf:/etc/opt/janusgraph/:ro"
    ports:
      - "8182:8182"